### ISSUE TITLE
Loot / Metaverse Character Composer page

### ISSUE THREAD

**Issue by Tudmotu** [xlootproject/xlootproject.github.io#4]
Hi all,
What do you think about adding a page on the website that will let people "compose" all their Loot NFTs together to create a "metaverse character"? They can then create a link and share with people.

Zemm on discord drew a  wireframe for such a page:
![image](https://user-images.githubusercontent.com/506487/132591420-e1e132b9-d5be-4856-81f9-0b4019771f2b.png)

Here is my suggestion for how it should work:

- There will be a "slot" for every token type - loot, character, companion, avatar, etc
- Users connect with wallet and can only compose tokens they own
- When you click on a "slot", a popup opens with a list of all the tokens the user owns that fit in that slot
- To determine which token fits in which slot, we will need to keep a mapping of collection -> type. This means we will not be able to just put a token ID like in the wireframe. And it means that every new collection that we want to add, we need to add it in the code (not much work, but requires maintenance)
- Users can create a link and a JPEG version of their "metaverse character"

WDYT?

**Comment by cambodious** [comment]
This is an awesome idea!! from here we can even build out a 3d viewer in high resolution! id say to start you would want to include the basics with probably loot bags and characters. ill add more in a bit I just wanted you to know that im here and ill help in anyway I can!

**Comment by Zemm111** [comment]
Yeah great idea, no need to enter token ID if its in your wallet and can be picked up by the app.  Thought people might like to try out other tokens with manual entry, to see what happens when they mix and match things they may want to buy, but could be a later add.

**Comment by Zemm111** [comment]
Little bit more about my own thinking, would consider this a "Gaming Lego" - this LARP Composer (name suggestion since its funny, and Character is already a deriv name) could be a foundational ratings synthesizer, allowing us to come up with correspondences from various NFTs and develop a discrete ratings system that can be used for various combat or war gaming apps.

**Comment by Tudmotu** [comment]
Glad you like the idea :)
1. @Zemm111 I get it now with entering token ids. I like it. I now think we should actually start without connecting a wallet - will be easier. In the future we can let people "sign" the character - only if they own every token
2. I guess "Stats", "Inventory" and "Avatar" are the basic slots we should start with. You mentioned "foes"  ("Arch Enemy"?), there is also "Companions". What other "slots" should we have?
3. Anyone knows what is the best way to find all the loot derivs?
4. Regarding naming it - if we don't want to use the term "character" wdyt about "Metaverse Avatar" or "Metaverse Persona"

More "selling points" for a tool like this:
1. It can help set "xLoot" as a main metaverse project and encourage collaboration with other derivs
2. This will allow people to compose bundles from common loot derivs to create a unique combo that is worth more than its parts. A "composite NFT" if you will

Also @CryptoSkelly , @ColinPlatt would love to hear what you think :)

**Comment by Zemm111** [comment]
Hey @Tudmotu -- awesome, yeah I love this!

I've been working on a spreadsheet that can be the starting point for how different derivs might combine to become overall ratings and mods for your character.  Going pretty well, will try to share tomorrow.

**re: You mentioned "Foes"**
Foes is a deriv I think is pretty good.  https://opensea.io/collection/foes
They are a collection of monsters, creatures and baddies, but I can see them being additive to a character, as well, i.e. beasts that the character can summon to fight along with them.  If you want to use labels that abstract them, in this case I'd call them "Summoned" for this particular use.

For naming, I still kinda like LARP, just because its more memeable and funny, and still gets the idea across pretty well.

Companions could be included too, for sure.  Will have to get to know them.  In general I think we should be somewhat selective in the derivs we use, but can start with a strong handful and see what makes sense.

**Comment by Tudmotu** [comment]
Ok, I got something basic working :)

https://tudmotu.github.io/xlootproject.github.io/pages/lootaverse-builder.html

I did it a bit differently than the original wireframe:
![image](https://user-images.githubusercontent.com/506487/132702693-2ac95b63-1877-41e9-bec2-8317e7732a10.png)

When you click on a button, a popup shows up and you can choose a token:
![image](https://user-images.githubusercontent.com/506487/132702998-d4d93391-ee5a-45ae-a7c7-a108f349bfc8.png)

And the final "character" looks like this:
![image](https://user-images.githubusercontent.com/506487/132702570-99a5723d-65bd-4dd6-8688-94307fa4d5e7.png)

We can update the list of collections and ask the community to add more. The collections are defined in JSON files that contain a list of collections with a "name" and a "contract" property:
https://github.com/Tudmotu/xlootproject.github.io/tree/feature/lootaverse-character-builder/js/lootaverse
![image](https://user-images.githubusercontent.com/506487/132716029-f29d822f-89bb-4893-a25b-4da0b3444f7c.png)


What do you think?

**Comment by Zemm111** [comment]
@Tudmotu this looks awesome!  IMO, this is a great Proof of concept for how these conceptually linked NFTs can be brought together.

For me, the most exciting thing is thinking about how game system ratings could be constructed by these composites in a rich way.  I've made a deep dive into xLoot items and terms, as well as several derivatives, and come up with a way that they can begin to construct a picture of an in game character, for a basic combat system.  

Posting it here!  LMK what you think about it!

https://docs.google.com/document/d/1yEyuZ6VGP47PFn5xqucJsU_s8Zw_eSZd5dv7gA81kqk/edit?usp=sharing

**Comment by Tudmotu** [comment]
Closing this issue as the PR was merged a couple of days ago :)
